name: NFCS_Read_Write
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  nfc_manager: ^4.0.2
  nfc_manager_ndef: ^1.0.1
  ndef_record: ^1.3.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0     # màn hình chờ (tool generate)
  flutter_launcher_icons: ^0.13.1   # logo app (tool generate)

flutter:
  uses-material-design: true
  assets:
    - assets/logo_2.png
    - assets/avatars/

# ========== CẤU HÌNH Ở CẤP CAO NHẤT (KHÔNG NẰM TRONG 'flutter:') ==========
flutter_native_splash:
  color: "#F0F1E3"
  image: assets/logo_2.png
  android_12:
    color: "#F0F1E3"
    image: assets/logo_2.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo_2.png
# ============================================================================
